apiVersion: v1
kind: Service
metadata:
  name: fwb-service
spec:
  type: ClusterIP
  # type: LoadBalancer
  selector:
    app: fwb-service
  ports:
    - protocol: TCP
      port: 8989
      targetPort: 8989